#! /usr/bin/env python

# AMFinder - amf
#
# MIT License
# Copyright (c) 2021 Edouard Evangelisti, Carl Turner
#               2024-2025 Royal Botanic Gardens, Kew
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

import amfinder_log as AmfLog
import amfinder_train as AmfTrain
import amfinder_config as AmfConfig
import amfinder_convert as AmfConvert
import amfinder_convert_tile_size as AmfConvertTileSize
import amfinder_convert_image_type as AmfConvertImageType
import amfinder_predict as AmfPredict
import amfinder_test as AmfTest
import amfinder_bald as AmfBald
import amfinder_colonisation as AmfColonisation
import amfinder_calibrate as AmfCalibrate
import amfinder_collapse_classes as AmfCollapse
import semisupervised_train as AmfSemiSupervisedTrain
import semisupervised_evaluate as AmfSemiSupervisedEvaluate
import torch


def main():

    AmfConfig.initialize()
    run_mode = AmfConfig.get("run_mode")
    semi_supervised = AmfConfig.get("semi_supervised")

    # Device Switch
    device = AmfConfig.get("device")  # e.g. 'cpu', 'cuda:0' or 'automatic'

    # Get the device setting
    if device == "automatic":
        if torch.cuda.is_available():
            AmfConfig.set("device", "cuda:0")
            AmfLog.text("Device set on automatic mode. Running via gpu")

        else:
            AmfConfig.set("device", "cpu")
            AmfLog.text(
                "Device set on automatic mode. CUDA ist not available. Running via cpu"
            )

    elif device == "cpu":
        AmfLog.text("Device manually set to cpu")

    elif device == "cuda:0" and torch.cuda.is_available():
        AmfLog.text("Device manually set to gpu")

    elif device == "cuda:0" and not torch.cuda.is_available():
        raise ValueError("Device manually set to gpu. CUDA not available")

    elif device not in ["cpu", "cuda:0", "cuda:1", "automatic"]:
        raise ValueError(
            'Invalid device. Set device to "cpu"", "cuda:0", "cuda:1", "automatic"'
        )

    AmfLog.text(f"Mode: {run_mode.upper()}")

    if run_mode == "train":
        AmfLog.text(f"Semi_Supervised: {semi_supervised}")

        if semi_supervised:
            AmfLog.text("Running semi-supervised training")
            AmfSemiSupervisedTrain.run(AmfConfig.get("root_path"))

        else:
            AmfLog.text("This is the normal training route")
            flag = AmfConfig.get("mlflow_flag")

            AmfLog.text(
                f"mlflow logging enabled" if flag else "mlflow logging disabled"
            )
            input_files = AmfConfig.get_input_files()
            get_tiles_for_labelling_using_active_learning = AmfConfig.get(
                "get_tiles_for_labelling_using_active_learning"
            )
            if get_tiles_for_labelling_using_active_learning:
                AmfLog.text(f"Running active learning to get tiles for labelling.")
                AmfBald.run(input_files)

            else:
                train_active_learning = AmfConfig.get("train_active_learning")
                AmfTrain.run(input_files, flag, train_active_learning)

    elif run_mode == "predict":
        input_files = AmfConfig.get_input_files()
        AmfPredict.run(input_files)

    elif run_mode == "test":
        if semi_supervised:
            AmfLog.text("Running semi-supervised evaluation")
            AmfSemiSupervisedEvaluate.run()
        else:
            input_files = AmfConfig.get_input_files()
            AmfTest.run(input_files)

    elif run_mode == "colonisation":
        AmfLog.text(f"Get colonisation percentage for annotations")
        input_files = AmfConfig.get_input_files()
        AmfColonisation.run(input_files)

    elif run_mode == "convert":
        input_files = AmfConfig.get_input_files()
        if AmfConfig.get("aggregate_tiles"):
            AmfConvertTileSize.run(input_files)
        elif AmfConfig.get("collapse"):
            AmfCollapse.run(input_files)
        else:
            AmfConvert.run(input_files)

    elif run_mode == "tifconversion":
        input_files = AmfConfig.get_input_files()
        AmfConvertImageType.run(input_files)

    elif run_mode == "calibrate":
        input_files = AmfConfig.get_input_files()
        AmfCalibrate.run(input_files)

    else:
        pass


if __name__ == "__main__":
    main()
