gpu_id: 0
dataset: "amf"
num_labeled: 50
expand_labels: true
arch: "cnn1"
epochs: 1
start_epoch: 0
batch_size: 2
lr: 0.008
warmup: 0
wdecay: 0.0005
nesterov: true
mu: 1
lambda_u: 1
T: 1
multiclass: False
threshold: 0.85
fixed_dataset: true
out: "fixmatch_results"
resume: false
seed: null
amp: false
opt_level: "O1"
prop_unlabelled: 1
local_rank: -1
no_progress: false
image_size: 252
num_classes: 6
